### ISSUE TITLE
Static compilation?

### ISSUE THREAD

**Issue by manveru** [tek/hix#1]
Is there a way to statically compile executables? I can't really find a good way to override the `devGhc` and the `haskellPackages` with `pkgs.pkgsCross.musl64.haskellPackages`.

**Comment by tek** [comment]
Hi there, thanks for the feedback, I haven't considered that use case before!
I added a new option, `devGhc.crossPkgs`, that allows you to specify a different base set using `devGhc.pkgs`.
I created an example test case using `musl64` and static executables: https://github.com/tek/hix/blob/main/test/cross/root/flake.nix
Appears to work, but if you have any suggestions for how to improve the API or if you're missing something, I'd be happy to implement that!

**Comment by tek** [comment]
For the record, a more "canonical" way of adding a static package could be:

```nix
outputs.packages.static = config.pkgs.haskell.lib.justStaticExecutables self.packages.${config.system}.root;
```
