### ISSUE TITLE
Support multiple libraries

### ISSUE THREAD

**Issue by cgeorgii** [tek/hix#4]
### Description

According to the [manual](https://tryp.io/hix/index.html):

> Packages may contain multiple components: an optional library and any number of executables, test suites or benchmarks (Cabal does support multiple libraries now, but Hix doesn’t yet).

The wording makes me believe that this is desirable to you as it would be to me, so I decided to open this ticket to track this effort and maybe help out.

`hpack` seems to support it via the `internal-libraries` field, as seen [here](https://github.com/sol/hpack#top-level-fields).

### Extra context
- [Announcement post for supporting multiple components in cabal](https://well-typed.com/blog/2023/03/cabal-multi-unit/)
- https://github.com/haskell/cabal/pull/8726
- [hpack: Quick-reference - Top-level fields](https://github.com/sol/hpack#top-level-fields)

**Comment by tek** [comment]
implemented!
