### ISSUE TITLE
Creating a new project fails due to missing dependency (pcre)

### ISSUE THREAD

**Issue by cgeorgii** [tek/hix#5]
### Description
Following the [manual](https://tryp.io/hix/index.html) and trying to create a new application fails as follows:

```sh
nix run 'github:tek/hix?ref=0.5.6#new' -- --name 'project-name' --author 'Author Name'
/tmp/tmp.jEmtd7he7o/hix: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
```

### Context
OS: `NixOS`

**Comment by tek** [comment]
ah, too bad 🙂 the binary used for generating the project is statically linked in a Github Action, so it was just a matter of time for this to happen, I guess.
